### ISSUE TITLE
submission threw an error

### ISSUE THREAD

**Issue by kellyhiser** [therabble/seattle-public-library-client#39]
uploaded 2 tracks - both look successful, but only "No Museums" plays; when I clicked "Finish submission" I got the error: "there was a problem saving your submission"

Album: testing testing
Chrome, 27 April 12:50 pm

JavaScript console:
![screen shot 2016-04-27 at 12 51 18 pm](https://cloud.githubusercontent.com/assets/8515447/14860444/df6f2300-0c76-11e6-85c9-52a9389c7a03.png)

**Comment by kellyhiser** [comment]
tried deleting the track in question, got the same error message.

**Comment by kellyhiser** [comment]
tested submitting in firefox, successfully uploaded a wav file, got the same error message when I clicked Finish.

Album title: Hee Haw

**Comment by mbrakken** [comment]
that error is on the submissions endpoint. that uses an auth token define
in config, since the notifications endpoint requires one and anonymous
folks can submit.

that auth token was mine, but that account got blown away when we swapped
in a different redis dump to move ccr data in. i'll create a new account
for myself.

**Comment by kellyhiser** [comment]
closing; @prestonaustin please reopen if there's a reason to do so.
